### ISSUE TITLE
du bist also mitglied in der jüdisch bolschewistischen weltverschwörung

### ISSUE THREAD

**Issue by u0nel** [asozialesnetzwerk/kaenguru-soundboard#6]
ich würds auch selbst machen, wenn mir jemand sagt wie ich das am einfachsten hinkrieg. (Ich hab alle CDs)

**Comment by Joshix-1** [comment]
Wenn du die als MP3-Dateien hast ist es Trivial. Vielleicht hilft folgende Seite dabei: https://www.how2shout.com/how-to/rip-audio-cd-to-mp3-on-windows-and-linux-without-any-third-party-software.html

**Comment by u0nel** [comment]
ne hab die cd und rhythmbox hat die cd irgendwie nicht erkannt. Und mit VLC war das auch irgendwie komisch

**Comment by Joshix-1** [comment]
https://asozial.org/kaenguru-soundboard/#-kapitel-11---j%C3%BCdisch-bolschewistische-weltverschw%C3%B6rung-ev
